# Generated by Django 4.1 on 2022-08-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojavirtualapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='data',
        ),
    ]
